### ISSUE TITLE
#1851 Feature: Extended Export CSV file

### ISSUE THREAD

**Issue by JNadeu** [eReuse/devicehub-teal#68]
Hacer un check general del fichero CSV que se genera al realizar el Export. Pendiente definir bien todas la columnas requeridas y el orden exacto en que se van a mostrar. De momento tenemos unos puntos claros que tendrían que aparecer en el fichero.

TODO. Añadir "SystemID"

- [x] -> System ID: 287

TODO. Añadir Public Link

- [x] -> Public Link: api.usody.com/usody/devices/338

TODO. Añadir el Hardware ID.

- [x] -> Hardware ID: "type-model-manufacturer-serialNumber"

TODO. En el tag mostrar si es named o unamed. Mostrar 3 Tags!

- [x] -> Tag 1 Type: "unamed" ( *TODO: need to implement issue #73)
- [x] -> Tag 1 ID: "BNYQ5"
- [x] -> Tag 1 Organization: "My Organization"

TODO. Añadir la fecha del último snapshot "Updated in".

* Falta definir bien como identificar el source de cada tipo de Action.
- [x] Registered (process): puede ser Software (WB) o Web (via formulario manual)
- [x] Updated in (software): la fecha del último snapshot subido.
- [x] Updated in (web): la fecha del último action realizado sobre el dispositivo

TODO. Report borrado, por cada HDD que se haya borrado en el último snapshot (NO poner discos que no salen en el erasure summary). hacer propuesta de como seria el borrado por reports.

- [x] -> Erasure Data Storage 1 S/N: "5VMHGK8W"
- [x] -> Erasure Data Storage 1 Size: "320 GB"
- [x] -> Erasure Data Storage 1 Software: "Workbench version 11.0b11"
- [x] -> Erasure Data Storage 1 Result: "Success / Failed"
- [x] -> Erasure Data Storage 1 Type: "Erase basic"

- [x] -> Erasure Data Storage 1 Steps: "Step 1: StepRandom 1:11:37, Step 2: StepRandom 1:11:37"
- [x] -> Erasure Data Storage 1 Steps Start Time: "Step 1: 2019-10-23T07:49:54.410830+00:00, Step 2: 2019-10-23T07:49:54.410830+00:00"
- [x] -> Erasure Data Storage 1 Steps End Time: "Step 1: 2019-10-23T07:49:54.410830+00:00, Step 2: 2019-10-23T07:49:54.410830+00:00"
- [x] -> Erasure Data Storage 1 Elapsed: "1:11:37 elapsed."
- [x] -> Erasure Data Storage 1 Method: "Shred, no standard."
- [x] -> Erasure Data Storage 1 Date: "Tue Oct 13 16:38:40 2020"

* Los siguientes campos se implementaran en otra iteración.

- [x] -> Benchmark RamSysbench (points): "6.0052"
- [x] -> Benchmark DataStorage Read Speed (MB/s) : "32,6"
- [x] -> Benchmark DataStorage Write Speed (MB/s) : "32,6"
- [x] -> Benchmark ProcessorSysbench (points): "10.4607"
- [x] -> Benchmark Processor (points): "22610.0"

TODO: Añadir Columnas del report del smart test. Por cada HDD

- [x] -> Test Data Storage 1 Software: "Workbench version"
- [x] -> Test Data Storage 1 Type "Short / Extended"
- [x] -> Test Data Storage 1 Result: "Success / Failed
- [x] -> Test Data Staorage 1 Power on (hours used): "18991"
- [x] -> Test Data Storage 1 Lifetime remaining (percentage): "2,17"

TODO: Añadir Columnas del report del Stress Test.

- [x] -> Test Stress Software: "Workbench version"
- [x] -> Test Stress Time (minutes): "10"

**TODO: Generar un CSV de pruebas (como ejemplo a seguir) para comprobar realmente se cumplen las especificaciones definidas anteriormente.**

**Comment by JNadeu** [comment]
It is necessary to make some adjustments on this issue, as when generating the csv, some component columns do not correspond.

Also change the order of some columns for a better reading of the file.

**Comment by dfranquesa** [comment]
I found several errors in: 
Column R, row 47 to 50
Column BQ, row 34 to 52
Column BV, several rows
Se attached file.
[Spreadsheet-errores.ods.zip](https://github.com/eReuse/devicehub-teal/files/5428597/Spreadsheet-errores.ods.zip)
